name: build

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image:
        required: true
        type: string
      platforms:
        type: string
        default: linux/arm64
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ inputs.registry }}/${{ inputs.image }}:${{ github.sha }}
            ${{ inputs.registry }}/${{ inputs.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
