name: deploy

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image:
        required: true
        type: string
      service:
        required: true
        type: string
    secrets:
      kube-config:
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Prepare deployment template
        uses: actions/checkout@v4
        with:
          repository: xingrz-dev/chart
          path: deploy

      - name: Set up kubectl
        uses: Azure/setup-kubectl@v4

      - name: Bake deployment
        id: bake
        uses: Azure/k8s-bake@v3
        with:
          renderEngine: helm
          helmChart: ./deploy/
          overrideFiles: ./deployment.yml
          overrides: |
            name:${{ inputs.service }}
            registry:${{ inputs.registry }}
            image:${{ inputs.image }}:${{ github.sha }}
          helm-version: latest

      - name: Prepare Kubernetes context
        uses: Azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.kube-config }}

      - name: Get deploy location
        id: deployment
        uses: KJ002/read-yaml@1.5
        with:
          file: ./deployment.yml
          key-path: '["location"]'

      - name: Deploy
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          strategy: basic
          namespace: app-${{ steps.deployment.outputs.data }}

      - name: Archive resource yaml
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ steps.deployment.outputs.data }}-${{ inputs.service }}-${{ github.sha }}
          path: ${{ steps.bake.outputs.manifestsBundle }}
